/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author Abyss
 */
public class Antecedentes extends javax.swing.JFrame {

    /**
     * Creates new form Antecedentes
     */
    public Antecedentes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_Ante_Edad = new javax.swing.JTextField();
        chk_Biopsias = new javax.swing.JCheckBox();
        chk_Ante_Benigno = new javax.swing.JCheckBox();
        chk_Ante_Maligno = new javax.swing.JCheckBox();
        chk_Ante_Atipia = new javax.swing.JCheckBox();
        chk_Ante_Tabaquismo = new javax.swing.JCheckBox();
        chk_Ante_Alcoholismo = new javax.swing.JCheckBox();
        chk_Ante_Toxicomanias = new javax.swing.JCheckBox();
        chk_CAmama = new javax.swing.JCheckBox();
        chk_Colon = new javax.swing.JCheckBox();
        chk_Ovario = new javax.swing.JCheckBox();
        chk_CACU = new javax.swing.JCheckBox();
        chk_Ant_Personal_CA_mama = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setText("Antecedentes de  Famiiliar Directo con:");

        jLabel1.setText("Edad");

        chk_Biopsias.setText("Biopsias previas de mama");

        chk_Ante_Benigno.setText("Benigno");

        chk_Ante_Maligno.setText("Maligno");

        chk_Ante_Atipia.setText("Atipia");

        chk_Ante_Tabaquismo.setText("Tabaquismo");

        chk_Ante_Alcoholismo.setText("Alcoholismo");

        chk_Ante_Toxicomanias.setText("Toxicomanias");

        chk_CAmama.setText("CA mama");

        chk_Colon.setText("Colon");

        chk_Ovario.setText("Ovario");

        chk_CACU.setText("CACU");

        chk_Ant_Personal_CA_mama.setText("Ant. Personal de CA de mama");

        jButton1.setText("Cancelar");

        jButton2.setText("Siguiente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chk_Biopsias)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chk_Ant_Personal_CA_mama)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Ante_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chk_Ante_Benigno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chk_Ante_Maligno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chk_Ante_Atipia))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(chk_Ante_Tabaquismo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chk_Ante_Alcoholismo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chk_Ante_Toxicomanias))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chk_CAmama)
                                .addGap(18, 18, 18)
                                .addComponent(chk_Colon)
                                .addGap(18, 18, 18)
                                .addComponent(chk_Ovario)
                                .addGap(18, 18, 18)
                                .addComponent(chk_CACU)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chk_CAmama)
                            .addComponent(chk_Colon)
                            .addComponent(chk_Ovario)
                            .addComponent(chk_CACU))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_Ante_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chk_Ant_Personal_CA_mama))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chk_Biopsias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chk_Ante_Benigno)
                            .addComponent(chk_Ante_Maligno)
                            .addComponent(chk_Ante_Atipia))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chk_Ante_Tabaquismo)
                            .addComponent(chk_Ante_Alcoholismo)
                            .addComponent(chk_Ante_Toxicomanias)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Antecedentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Antecedentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Antecedentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Antecedentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Antecedentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chk_Ant_Personal_CA_mama;
    private javax.swing.JCheckBox chk_Ante_Alcoholismo;
    private javax.swing.JCheckBox chk_Ante_Atipia;
    private javax.swing.JCheckBox chk_Ante_Benigno;
    private javax.swing.JCheckBox chk_Ante_Maligno;
    private javax.swing.JCheckBox chk_Ante_Tabaquismo;
    private javax.swing.JCheckBox chk_Ante_Toxicomanias;
    private javax.swing.JCheckBox chk_Biopsias;
    private javax.swing.JCheckBox chk_CACU;
    private javax.swing.JCheckBox chk_CAmama;
    private javax.swing.JCheckBox chk_Colon;
    private javax.swing.JCheckBox chk_Ovario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_Ante_Edad;
    // End of variables declaration//GEN-END:variables
}
