/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
/**
 *
 * @author Abyss
 */
public class Cita_Impresion_Comentarios extends javax.swing.JFrame {

    public Connection con = null;
    public Statement st=null;
    public String bd = "Mastologia";   
    //asegurate de cambiar esto por el nombre tu usuario en mysql
    public String login = "root"; 
    //aqui escribe la contraseña de ese usuario
    public String password = "luna16";
    public String url = "jdbc:mysql://localhost/"+bd;
    /**
     * Creates new form Cita_Impresion_Comentarios
     */
    public Cita_Impresion_Comentarios() {
        initComponents();
        
        java.util.Calendar fecha = Calendar.getInstance();
              
        JDCitaSubsecuente.setDate(fecha.getTime());
        
        try {
        
        Class.forName("org.gjt.mm.mysql.Driver");
        con = DriverManager.getConnection(url, login, password);
        if (con != null)
        {
            System.out.println("Yeah, hemos conectado con  "+url+" ... Ok");
            st=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            //conn.close();
        }
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Rayos!!! Hubo un problema al conectar con la base" + url);
        }catch(ClassNotFoundException ex) {
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JDCitaSubsecuente = new org.jdesktop.swingx.JXDatePicker();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chk_Res_Pat_Benigna = new javax.swing.JCheckBox();
        chk_Res_Sospechosa = new javax.swing.JCheckBox();
        chk_Envio_Onco_mama = new javax.swing.JCheckBox();
        chk_Envia_Clin_Pato_Benigna = new javax.swing.JCheckBox();
        chk_Envio_Seguimiento_Anual = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        chk_Alto = new javax.swing.JCheckBox();
        chk_Promedio = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        chk_OncoMama = new javax.swing.JCheckBox();
        chk_PatBenigna = new javax.swing.JCheckBox();
        chk_SeguimientoAnual = new javax.swing.JCheckBox();
        chk_Estudios_Complementarios = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComentarios = new javax.swing.JTextArea();
        btnFinalizar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Cita Subsecuente");

        jLabel4.setText("Fecha");

        jLabel5.setText("Resulado:");

        jLabel6.setText("Enviado a:");

        chk_Res_Pat_Benigna.setText("Pat.Benigna");

        chk_Res_Sospechosa.setText("Sospechosa");

        chk_Envio_Onco_mama.setText("Onco Mama");

        chk_Envia_Clin_Pato_Benigna.setText("Clin.Pato.Benigna");

        chk_Envio_Seguimiento_Anual.setText("Seguimiento anual");

        jLabel1.setText("Impresion de Riesgo");

        chk_Alto.setText("Alto");

        chk_Promedio.setText("Promedio");

        jLabel2.setText("Plan Clinica");

        chk_OncoMama.setText("Onco Mama");

        chk_PatBenigna.setText("Pat.Benigna");

        chk_SeguimientoAnual.setText("Seguimiento Anual");

        chk_Estudios_Complementarios.setText("Estudios Complementarios");

        jLabel7.setText("Comentario");

        txtComentarios.setColumns(20);
        txtComentarios.setRows(5);
        jScrollPane1.setViewportView(txtComentarios);

        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        jButton2.setText("Atras");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chk_OncoMama)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chk_PatBenigna)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chk_SeguimientoAnual)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chk_Estudios_Complementarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(chk_Envio_Seguimiento_Anual)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(chk_Envio_Onco_mama)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(chk_Envia_Clin_Pato_Benigna))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel5)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(chk_Res_Pat_Benigna))
                                                    .addComponent(jLabel3))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(chk_Res_Sospechosa)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel4)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(JDCitaSubsecuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(chk_Alto)
                                                .addGap(18, 18, 18)
                                                .addComponent(chk_Promedio)))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(43, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFinalizar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(JDCitaSubsecuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chk_Res_Pat_Benigna)
                    .addComponent(chk_Res_Sospechosa)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chk_Envio_Onco_mama)
                            .addComponent(chk_Envia_Clin_Pato_Benigna)
                            .addComponent(chk_Alto)
                            .addComponent(chk_Promedio))
                        .addGap(7, 7, 7)
                        .addComponent(chk_Envio_Seguimiento_Anual))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6)))
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chk_OncoMama)
                    .addComponent(chk_PatBenigna)
                    .addComponent(chk_SeguimientoAnual)
                    .addComponent(chk_Estudios_Complementarios))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(btnFinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        
       
        String FECHA_CITA;
        int RESULTADOPATBENIGNA=0, RESULTADOSOSPECHOSA=0, ENVIO_ONCO=0, ENVIO_CLIN_PAT_BENIGNA=0, ENVIO_SEGUIMIENTO_ANUAL=0,maxId=0;       
        
        DateFormat myformat = new SimpleDateFormat("yyyy-MM-dd");
                       
        FECHA_CITA = myformat.format(JDCitaSubsecuente.getDate());
        if (chk_Res_Pat_Benigna.isSelected() == true) { RESULTADOPATBENIGNA = 1;  }
        if (chk_Res_Sospechosa.isSelected() == true) { RESULTADOSOSPECHOSA = 1;  }
        if (chk_Envio_Onco_mama.isSelected() == true) { ENVIO_ONCO = 1; }
        if (chk_Envia_Clin_Pato_Benigna.isSelected() == true) { ENVIO_CLIN_PAT_BENIGNA = 1; }
        if (chk_Envio_Seguimiento_Anual.isSelected() == true) { ENVIO_SEGUIMIENTO_ANUAL = 1; }
        
        int RIESGOALTO=0, RIESGOPROMEDIO=0;

        int PLAN_CLINICA_ONCO=0, PLAN_PAT_BENIGNA=0, PLAN_SEGUIMIENTO_ANUAL=0, PLAN_ESTUDIOS_COMPLEMENTARIOS=0;
        String COMENTARIOS;
        
        if (chk_Alto.isSelected() == true) { RIESGOALTO = 1;  }
        if (chk_Promedio.isSelected() == true) { RIESGOPROMEDIO = 1;  }
        
        if (chk_OncoMama.isSelected() == true) { PLAN_CLINICA_ONCO = 1; }
        if (chk_PatBenigna.isSelected() == true) { PLAN_PAT_BENIGNA = 1; }
        if (chk_SeguimientoAnual.isSelected() == true) { PLAN_SEGUIMIENTO_ANUAL = 1; }
        if (chk_Estudios_Complementarios.isSelected() == true) { PLAN_ESTUDIOS_COMPLEMENTARIOS = 1; }
        COMENTARIOS = txtComentarios.getText();
              
        
        try{
            Statement sentencia = null;
            ResultSet resultados = null;
            sentencia=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);

            resultados = sentencia.executeQuery("SELECT MAX(`IdDatos_Paciente`) as maxid FROM `Datos_Paciente`" );
//            
            while( resultados.next() )
            {
                maxId = resultados.getInt("maxid");
            }
            String query = "INSERT INTO `Cita`(`IdDatos_PacienteFK`, `Fecha_Cita`, `Res_Pat_Benigna`, `Res_Sospechosa`, `Envio_Onco_Mama`, `Envio_Clinica_Pat_Benigna`, `Envio_Seguimiento`) "
                    + "VALUES (?,?,?,?,?,?,?)";
            PreparedStatement preparedStmt = con.prepareStatement(query);
            preparedStmt.setInt(1, maxId);
            preparedStmt.setString(2, FECHA_CITA);
            preparedStmt.setInt(3, RESULTADOPATBENIGNA);
            preparedStmt.setInt(4, RESULTADOSOSPECHOSA);
            preparedStmt.setInt(5, ENVIO_ONCO);
            preparedStmt.setInt(6, ENVIO_CLIN_PAT_BENIGNA);
            preparedStmt.setInt(7, ENVIO_SEGUIMIENTO_ANUAL);
            
            preparedStmt.execute();
            
            query = "INSERT INTO `Impresion_Riesgo`(`IdDatos_PacienteFK`, `Alto`, `Promedio`) "
                    + "VALUES (?,?,?)";
            preparedStmt = con.prepareStatement(query);
            preparedStmt.setInt(1, maxId);
            preparedStmt.setInt(2, RIESGOALTO);
            preparedStmt.setInt(3, RIESGOPROMEDIO);
                       
            preparedStmt.execute();  
          
            query = "INSERT INTO `Plan_Clinica`(`IdDatos_PacienteFK`, `Onco_Mama`, `Pat_Benigna`, `Seguimiento_Anual`, `Estudios_Complementarios`, `Comentario`) "
                    + "VALUES (?,?,?,?,?,?)";
            preparedStmt = con.prepareStatement(query);
            preparedStmt.setInt(1, maxId);
            preparedStmt.setInt(2, PLAN_CLINICA_ONCO);
            preparedStmt.setInt(3, PLAN_PAT_BENIGNA);
            preparedStmt.setInt(4, PLAN_SEGUIMIENTO_ANUAL);
            preparedStmt.setInt(5, PLAN_ESTUDIOS_COMPLEMENTARIOS);
            preparedStmt.setString(6, COMENTARIOS);
            
            preparedStmt.execute();  
            
            
            
            
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Rayos!!! Hubo un problema al conectar con la base");
        }
        
    }//GEN-LAST:event_btnFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cita_Impresion_Comentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cita_Impresion_Comentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cita_Impresion_Comentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cita_Impresion_Comentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cita_Impresion_Comentarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker JDCitaSubsecuente;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JCheckBox chk_Alto;
    private javax.swing.JCheckBox chk_Envia_Clin_Pato_Benigna;
    private javax.swing.JCheckBox chk_Envio_Onco_mama;
    private javax.swing.JCheckBox chk_Envio_Seguimiento_Anual;
    private javax.swing.JCheckBox chk_Estudios_Complementarios;
    private javax.swing.JCheckBox chk_OncoMama;
    private javax.swing.JCheckBox chk_PatBenigna;
    private javax.swing.JCheckBox chk_Promedio;
    private javax.swing.JCheckBox chk_Res_Pat_Benigna;
    private javax.swing.JCheckBox chk_Res_Sospechosa;
    private javax.swing.JCheckBox chk_SeguimientoAnual;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtComentarios;
    // End of variables declaration//GEN-END:variables
}
