/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author Abyss
 */
public class Estudios_Factores_Resultados extends javax.swing.JFrame {

    /**
     * Creates new form Estudios_Factores_Resultados
     */
    public Estudios_Factores_Resultados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDFechaUltra = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        chk_Mamas_Densas = new javax.swing.JCheckBox();
        chk_Protesis = new javax.swing.JCheckBox();
        chk_CuerposExtraños = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        chk_Benigno = new javax.swing.JCheckBox();
        chk_Maligno = new javax.swing.JCheckBox();
        chk_Atipia = new javax.swing.JCheckBox();
        chk_Estudio_Mastologia = new javax.swing.JCheckBox();
        chk_Estudio_Ultrasonido = new javax.swing.JCheckBox();
        chk_BIRADS_Masto = new javax.swing.JCheckBox();
        chk_BIRADS_Ultra = new javax.swing.JCheckBox();
        chk_No_estudios = new javax.swing.JCheckBox();
        JDFechaMasto = new org.jdesktop.swingx.JXDatePicker();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Factores de Riesgo Asociado");

        chk_Mamas_Densas.setText("Mamas Densas");

        chk_Protesis.setText("Protesis");

        chk_CuerposExtraños.setText("Cuerpos extraños en mama");

        jLabel2.setText("Resultado de Patologia");

        chk_Benigno.setText("Benigno");

        chk_Maligno.setText("Maligno");

        chk_Atipia.setText("Atipia");

        chk_Estudio_Mastologia.setText("Mastografia");

        chk_Estudio_Ultrasonido.setText("Ultrasonido");

        chk_BIRADS_Masto.setText("BIRADS");

        chk_BIRADS_Ultra.setText("BIRADS");

        chk_No_estudios.setText("No hay estudios");

        jLabel7.setText("Estudios");

        jButton1.setText("Siguiente");

        jButton2.setText("Atras");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chk_Estudio_Ultrasonido)
                                .addGap(18, 18, 18)
                                .addComponent(JDFechaUltra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chk_Estudio_Mastologia)
                                .addGap(18, 18, 18)
                                .addComponent(JDFechaMasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chk_BIRADS_Masto)
                                .addGap(18, 18, 18)
                                .addComponent(chk_No_estudios))
                            .addComponent(chk_BIRADS_Ultra)))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chk_Mamas_Densas)
                        .addGap(18, 18, 18)
                        .addComponent(chk_Protesis)
                        .addGap(18, 18, 18)
                        .addComponent(chk_CuerposExtraños))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chk_Benigno)
                        .addGap(18, 18, 18)
                        .addComponent(chk_Maligno)
                        .addGap(18, 18, 18)
                        .addComponent(chk_Atipia))
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chk_Estudio_Mastologia)
                    .addComponent(chk_BIRADS_Masto)
                    .addComponent(chk_No_estudios)
                    .addComponent(JDFechaMasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chk_Estudio_Ultrasonido)
                        .addComponent(JDFechaUltra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chk_BIRADS_Ultra))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chk_Mamas_Densas)
                    .addComponent(chk_Protesis)
                    .addComponent(chk_CuerposExtraños))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chk_Benigno)
                    .addComponent(chk_Maligno)
                    .addComponent(chk_Atipia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estudios_Factores_Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estudios_Factores_Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estudios_Factores_Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estudios_Factores_Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estudios_Factores_Resultados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker JDFechaMasto;
    private org.jdesktop.swingx.JXDatePicker JDFechaUltra;
    private javax.swing.JCheckBox chk_Atipia;
    private javax.swing.JCheckBox chk_BIRADS_Masto;
    private javax.swing.JCheckBox chk_BIRADS_Ultra;
    private javax.swing.JCheckBox chk_Benigno;
    private javax.swing.JCheckBox chk_CuerposExtraños;
    private javax.swing.JCheckBox chk_Estudio_Mastologia;
    private javax.swing.JCheckBox chk_Estudio_Ultrasonido;
    private javax.swing.JCheckBox chk_Maligno;
    private javax.swing.JCheckBox chk_Mamas_Densas;
    private javax.swing.JCheckBox chk_No_estudios;
    private javax.swing.JCheckBox chk_Protesis;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
